# Site settings
title: simplesmente
description: "diligÃªncia, progresso e Verdade"
url: "https://arthurpaulino.github.io"
author:
  name: "Arthur Paulino"
  email: "arthurleonardo.ap@gmail.com"
  url: "https://github.com/arthurpaulino"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
reverse: false
